use_frameworks!

platform :ios, '8.0'

target 'LHlocalizationTool_Example' do
  pod 'LHlocalizationTool', :path => '../'

  target 'LHlocalizationTool_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
  end
end
